menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Blog Posts', url: '/blog-posts'}
- {name: 'About', url: '/about'}

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/jswu18'}
- {icon: 'envelope', link: 'mailto:jian.wu.22@ucl.ac.uk'}
- {icon: 'github', link: 'https://github.com/jswu18'}
